name: FTP Deploy Source Code

on:
  push:
    branches: [ "main" ]

jobs:
  main:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 📂 NPM Install and Build
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.misterprada.com
          local-dir: ./dist/
          server-dir: /e2.misterprada.com/
          username: ${{ vars.PRODUCTION_FTP_USERNAME }}
          password: ${{ secrets.PRODUCTION_FTP_PASSWORD }}
